set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

if(NOT RGDS_SYSROOT)
	set(RGDS_SYSROOT "/tmp/rgds-sysroot")
endif()

set(CMAKE_FIND_ROOT_PATH "${RGDS_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

set(CMAKE_DISABLE_FIND_PACKAGE_PkgConfig ON)
set(PKG_CONFIG_EXECUTABLE "" CACHE FILEPATH "Disabled for aarch64 cross builds")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,-rpath-link,${RGDS_SYSROOT}/usr/lib")
set(CMAKE_SKIP_BUILD_RPATH TRUE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
